export const classe3Projects = [
    {
        companyName: 'Tiwi',
        logoSrc: 'https://raw.githubusercontent.com/nilaerdna/nilaerdna.github.io/master/2018-2019/logos/tiwi.png',
        websiteName: 'tiwi.it',
        websiteLink: 'https://tiwi.it/',
        description: 'TIWI racconta per immagini. Spiega, sorprende, appassiona. Siamo uno studio creativo specializzato nell’ideazione e produzione di contenuti video e interattivi, per il web e la televisione.',
        timestamp: '07:00 - 7 gen 2019',
        projectRoute: '#/3/tiwi',
    },
    {
        companyName: "KatanaCa'",
        logoSrc: 'https://raw.githubusercontent.com/nilaerdna/nilaerdna.github.io/master/2018-2019/logos/katanaca.png',
        websiteName: 'katanaca.com',
        websiteLink: 'https://katanaca.com/',
        description: "KatanaCa', l'altro modo di trovare casa. Cerca casa attraverso le offerte immobili delle migliori agenzie immobiliari.",
        timestamp: '07:00 - 10 gen 2019',
        projectRoute: '#/3/katanaca',
    },
    {
        companyName: 'Energy Way',
        logoSrc: 'https://raw.githubusercontent.com/nilaerdna/nilaerdna.github.io/master/2018-2019/logos/energyway.png',
        websiteName: 'energyway.it',
        websiteLink: 'https://energyway.it',
        description: "The energy, the science, the art of data. Offriamo servizi di Data Science per l'ottimizzazione dei processi aziendali.",
        timestamp: '07:00 - 14 gen 2019',
        projectRoute: '#/3/energyway',
    },
    {
        companyName: 'Webranking',
        logoSrc: 'https://raw.githubusercontent.com/nilaerdna/nilaerdna.github.io/master/2018-2019/logos/webranking.png',
        websiteName: 'webranking.it',
        websiteLink: 'https://webranking.it',
        description: 'Siamo la maggiore search agency indipendente italiana e offriamo consulenza strategica di digital marketing attraverso attività di media planning, experience design e data intelligence.',
        timestamp: '07:00 - 17 gen 2019',
        projectRoute: '#/3/webranking',
    },
    {
        companyName: 'Errevi System',
        logoSrc: 'https://raw.githubusercontent.com/nilaerdna/nilaerdna.github.io/master/2018-2019/logos/errevisystem.png',
        websiteName: 'errevi.com',
        websiteLink: 'https://errevi.com',
        description: 'Errevi System valorizza le persone dando loro fiducia e permettendogli di assumersi delle responsabilità, le rendiamo parte attiva delle dinamiche aziendali e diamo loro la possibilità di mettersi in gioco.',
        timestamp: '07:00 - 21 gen 2019',
        projectRoute: '#/3/errevi',
    },
    {
        companyName: 'Monta Smonta',
        logoSrc: 'https://raw.githubusercontent.com/nilaerdna/nilaerdna.github.io/master/2018-2019/logos/montasmonta.png',
        websiteName: 'pascal.edu.it',
        websiteLink: 'http://pascal.edu.it/',
        description: "Il BUS nacque nel 1974 come progetto di un biennio sperimentale unico, gli indirizzi disponibili sono: l'Indirizzo Grafico, Informatico, Relazioni Internazionali e Scienze Applicate.",
        timestamp: '07:00 - 2 mar 2019',
        projectRoute: '#/3/montasmonta',
    },
    {
        companyName: 'Leonardo da Vinci',
        logoSrc: 'https://raw.githubusercontent.com/nilaerdna/nilaerdna.github.io/master/2018-2019/logos/leonardodavinci.png',
        websiteName: 'icdavincireggioemilia.edu.it',
        websiteLink: 'https://icdavincireggioemilia.edu.it/',
        description: 'Istituto Comprensivo "Leonardo da Vinci" di Reggio Emilia.',
        timestamp: '14:30 - 27 feb 2019',
        projectRoute: '#/3/leonardodavinci',
    },
    {
        companyName: 'Accenture',
        logoSrc: 'https://raw.githubusercontent.com/nilaerdna/nilaerdna.github.io/master/2018-2019/logos/accenture.png',
        websiteName: 'accenture.com',
        websiteLink: 'https://accenture.com/',
        description: "Accenture libera nuove opportunità in Italia, sfruttando il potenziale rivoluzionario dell'innovazione in ogni settore, in ogni paese, ogni giorno.",
        timestamp: '10:00 - 9 apr 2019',
        projectRoute: '#/3/accenture',
    },
    {
        companyName: 'Università di Parma',
        logoSrc: 'https://raw.githubusercontent.com/nilaerdna/nilaerdna.github.io/master/2018-2019/logos/unipr.png',
        websiteName: 'tomamic.github.io',
        websiteLink: 'https://tomamic.github.io/',
        description: "L'Università degli Studi di Parma è un'università statale, fra le più antiche del mondo.",
        timestamp: '09.00 - 10 giu 2019',
        projectRoute: '#/3/unipr',
    },
];
